COMMENT_S = [
    "Love your feed! 😍",
    "Beautiful! 😍",
    "This is amazing! 😍",
    "Great content! 👌",
    "Your photos are stunning! 😍",
    "I love this post! ❤️",
    "Keep up the great work! 👍",
    "Awesome content! 😎",
    "This is so inspiring! 💪",
    "Your posts are always amazing! 😍",
    "Thanks for sharing this! 🙌",
    "I just followed you, can't wait for more! 👀",
    "Your style is on point! 🔥",
    "Wow, just wow! 😍",
    "This is so cool! 😎",
    "Incredible! 😍",
    "This is goals! 🔥",
    "I'm obsessed with your feed! 😍",
    "Your creativity is inspiring! 🙌",
    "Amazing work! 👏",
    "Thanks for brightening up my day with this post! ☀️",
    "I'm loving your content! ❤️",
    "This is so beautiful! 😍",
    "You are killing it! 🔥",
    "I love your unique perspective! 🤩",
    "This is just awesome! 😎",
    "You have a great eye for photography! 👌",
    "I'm definitely trying this out! 👍",
    "Your hard work is paying off! 👏",
    "Thanks for sharing your talent with us! 🙏",
    "I'm blown away by this post! 😍",
    "This is so inspiring, keep it up! 💪",
    "You deserve all the success, keep going! 👊",
    "This is definitely going in my saved folder! 💾",
    "Your posts are always so creative! 🤩",
    "This is what Instagram was made for! 😎",
    "I can't get enough of your content! 😍",
    "This post just made my day! ☀️",
    "This is fire! 🔥",
    "Your attention to detail is incredible! 👌",
    "I'm so glad I found your page! ❤️",
    "This is so unique and cool! 😎",
    "I'm learning so much from your content! 🤓",
    "This post deserves all the love! ❤️",
    "This is art! 🎨",
    "You have a great sense of humor! 😂",
    "This is so relatable, I love it! 😍",
    "Your passion shines through in your content! 🌟",
    "I'm always excited to see your new posts! 🤩",
    "This is so well done! 👏",
    "I'm blown away by your creativity! 🤯",
    "You are a true inspiration! 🙌",
    "This post is pure gold! 💰",
    "You have a great energy in your content! ⚡️",
    "This is so motivational, thank you! 💪",
    "You are one of my favorite accounts on Instagram! 😍",
    "I'm so happy I stumbled upon your page! ❤️",
    "This is genius! 🤯",
    "Your posts always make me smile! 😄",
    "This is so dreamy! 😍",
    "You have a great way with words! 📝",
    "This is so clever, I love it! 🤩" ]


messages = [
    "Hey there! I just discovered your page and I'm loving your content. Keep up the great work!",
    "Your posts are so inspiring! Thank you for sharing your creativity with us.",
    "I just followed you and I'm excited to see more of your amazing content!",
    "You have such a unique perspective and I love it! Your posts are always so refreshing to see on my feed.",
    "Your hard work and dedication is truly paying off! Keep going!",
    "Your posts always brighten up my day. Thank you for spreading positivity and creativity on Instagram!",
    "I love your style and creativity. Your posts are always so on point!",
    "I'm always excited to see what you'll post next. You have such a great eye for photography!",
    "Thank you for being such an inspiration. Your posts always motivate me to keep pushing forward.",
    "I just wanted to say that I'm a huge fan of your page. Keep up the amazing work!",
    "Your posts always make me smile. Thank you for bringing a little bit of joy to my day!",
    "I'm so glad I stumbled upon your page. You have such a talent for creating beautiful content.",
    "Your posts are like a breath of fresh air on my Instagram feed. Thank you for sharing your creativity with us!",
    "I love how you're able to make even the simplest things look so beautiful. Your posts are always so aesthetically pleasing!",
    "Your hard work and dedication is truly inspiring. Thank you for being a role model for us all!",
    "Your posts always inspire me to be more creative. Thank you for sharing your talent with us!",
    "I just wanted to reach out and say that I'm a huge fan of your page. Your content always puts me in a good mood!",
    "Your posts are like a ray of sunshine on my Instagram feed. Thank you for brightening up my day!",
    "I love your style and aesthetic. Your posts are always so on brand and consistent!",
    "Your posts always make me feel so inspired and motivated. Thank you for being such a positive influence on Instagram!",
    "I'm so impressed by your creativity and talent. Your posts are always so unique and interesting to look at!",
    "Thank you for sharing your passion and creativity with us. Your posts always make me feel inspired to pursue my own passions!",
    "I just followed you and I'm already obsessed with your content. You have such a talent for creating beautiful visuals!",
    "Your posts are always so well thought out and executed. Thank you for sharing your creativity with us!",
    "I just wanted to say that your posts always bring a little bit of joy to my day. Thank you for being a bright spot on Instagram!",
    "Your posts always stand out on my feed. Thank you for sharing your unique perspective with us!",
    "I'm always excited to see what you'll come up with next. Your posts are always so creative and interesting!",
    "Thank you for being such a positive force on Instagram. Your posts always make me feel more optimistic and inspired!",
    "Your posts always remind me that there is beauty to be found in the everyday. Thank you for sharing your creativity with us!",
    "I love how you're able to capture such beautiful moments and turn them into stunning visuals. Your posts are always so breathtaking!",
    "Your posts always make me feel more connected to the world around me. Thank you for being such a talented and thoughtful creator!",
    "Your posts always put a smile on my face. Thank you for spreading happiness and positivity on Instagram!"]
 
 
 
